port: 11570
seeds:
  use_seeds: True
  id: 42

data:
  dataset: AirLab
  data_path:
      car:
      drone:
      dog:
      human: ./data/new_lamar_split/human/

  use_local_coord: True
  train_dir: train
  test_dir: test
  validation_dir: val

  random_partition: False
  data_rate: 1.0
  train_rate: 0.85
  test_rate: 0.15
  valid_rate: 0.15

  imu_freq: 200.0
  sample_freq: 40

  gravity_alignment:
    enabled: False
    magnitude: 9.8101
    direction: [0, 0, -1]
    enable_validation: False
    visualize: False

augment:
  feat_acc_sigma: 0.0001
  feat_gyr_sigma: 0.00001
  add_bias_noise: True
  accel_bias_range: 0.1
  gyro_bias_range: 0.002
  add_gravity_noise: True
  gravity_noise_theta_range: 5

model:
  model_name: Foundation_Model
  model_yaml: 'config/resnet_lstm_multihead.yaml'
  pred_velocity: True
  adapter: False

train:
  out_dir: ./data/outputs/lamar_full/
  use_pretrain_model: False
  use_multi_gpu: False
  use_amp: True
  batch_size: 128
  epochs: 20
  start_cov_epochs: 999
  n_workers: 16
  seq_len: 10
  predict_start: 0
  predict_end: 10
  add_noise: True
  active_heads: ["human"]

  optimizer:
    learning_rate: 0.0005
    method: Adam
    weight_decay: 0.01

  scheduler:
    factor: 0.1
    patience: 10

val:
  batch_size: 256
  n_workers: 4

test:
  out_dir: ./data/outputs/lamar_full/
  n_workers: 2

schemes:
  train: True
  test: False
  online_adaption: False
