model_param:
  input_dim: 6
  output_dim: 3
  split_z: True
  past_time: 0.0
  window_time: 1.0
  future_time: 0.0
  layer_sizes: [ 2, 2, 2, 2 ]
  drop_ratio: 0.5
  lstm_size: 64 #originla 256
  lstm_layers: 1
  lstm_dropout: 0.0 #originla 0.0
  use_transformer: False
